# Generated by Django 4.2.7 on 2025-11-28 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0007_remove_customuser_bandwidth_limit_and_more"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.AlterModelOptions(
            name="paystackconfiguration",
            options={
                "verbose_name": "Paystack Configuration",
                "verbose_name_plural": "Paystack Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["price"]},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="isp_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paystack_subaccount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="platform_fee",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="tenant",
        ),
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paystackconfiguration",
            name="public_key",
            field=models.CharField(
                default="pk_test_326928d62c0d19eaa90341289573887d07a5c96c",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paystackconfiguration",
            name="secret_key",
            field=models.CharField(
                default="sk_test_cbba1d96dd613f76cfa45a5409fbc9bc3712db43",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paystackconfiguration",
            name="transaction_charge",
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paystack_access_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="billing.subscriptionplan",
            ),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="account_name",
            field=models.CharField(
                help_text="Name of the Paystack account", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="account_number",
            field=models.CharField(
                blank=True, help_text="Bank account number", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="bank_code",
            field=models.CharField(
                blank=True,
                help_text="Bank code from Paystack",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="subaccount_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paystack_configs",
                to="accounts.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="billing.subscriptionplan",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="bandwidth",
            field=models.IntegerField(help_text="Mbps"),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="data_cap",
            field=models.IntegerField(
                blank=True, help_text="GB (leave blank for unlimited)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="duration_days",
            field=models.IntegerField(
                default=30, help_text="Subscription duration in days"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_plans",
                to="accounts.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paystackconfiguration",
            unique_together={("tenant", "is_active")},
        ),
        migrations.AlterModelTable(
            name="payment",
            table="billing_payment",
        ),
        migrations.AlterModelTable(
            name="subscription",
            table="subscriptions",
        ),
    ]
