# Generated by Django 4.2.7 on 2025-12-06 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0012_alter_tenant_options_tenant_bank_details_and_more"),
        ("billing", "0003_alter_subscriptionplan_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkDataPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Package"),
                            ("premium", "Premium Package"),
                            ("unlimited", "Unlimited Package"),
                            ("custom", "Custom Package"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "data_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Data amount in GB", max_digits=10
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "validity_days",
                    models.IntegerField(
                        default=30, help_text="Package validity in days"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform Inventory"),
                            ("vendor_direct", "Vendor Direct Sale"),
                            ("vendor_marketplace", "Vendor Marketplace"),
                            ("isp_upload", "ISP Uploaded Invoice"),
                        ],
                        default="platform",
                        max_length=20,
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost to platform/vendor",
                        max_digits=10,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price to ISP", max_digits=10
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission_included",
                    models.BooleanField(
                        default=True,
                        help_text="Whether commission is included in price",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.5,
                        help_text="Commission percentage for this package",
                        max_digits=5,
                    ),
                ),
                (
                    "platform_margin",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                (
                    "platform_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, available to all ISPs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "bulk_data_packages",
                "ordering": ["selling_price"],
            },
        ),
        migrations.CreateModel(
            name="DataVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=100)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "agreement_start",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("agreement_end", models.DateField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("bulk_data", "Bulk Data Sales"),
                            ("subscription", "Subscription Sales"),
                            ("topup", "Data Top-ups"),
                            ("payment_processing", "Payment Processing"),
                            ("all", "All Services"),
                        ],
                        default="bulk_data",
                        max_length=50,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.5,
                        help_text="Commission percentage (e.g., 7.5 for 7.5%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applies_to_all",
                    models.BooleanField(
                        default=True, help_text="Applies to all ISPs if True"
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of Total"),
                            ("fixed", "Fixed Amount"),
                            ("tiered", "Tiered Percentage"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum amount for this tier",
                        max_digits=10,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount for this tier",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific ISP if applies_to_all is False",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Commission",
                "verbose_name_plural": "Platform Commissions",
                "db_table": "platform_commissions",
                "unique_together": {("service_type", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="ISPBulkPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, help_text="Number of packages purchased"
                    ),
                ),
                (
                    "total_data",
                    models.DecimalField(
                        decimal_places=2, help_text="Total data in GB", max_digits=15
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing Distribution"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform commission amount",
                        max_digits=10,
                    ),
                ),
                (
                    "isp_net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount ISP receives after commission",
                        max_digits=10,
                    ),
                ),
                ("commission_calculated", models.BooleanField(default=False)),
                ("auto_distribute", models.BooleanField(default=True)),
                (
                    "distribute_to",
                    models.CharField(
                        choices=[
                            ("all", "All Active Customers"),
                            ("prepaid", "Prepaid Customers Only"),
                            ("postpaid", "Postpaid Customers Only"),
                            ("custom", "Selected Plans Only"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "distribution_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "distribution_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.bulkdatapackage",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_purchases",
                        to="billing.payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_purchases",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "isp_bulk_purchases",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="DataDistributionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Data allocated in GB",
                        max_digits=10,
                    ),
                ),
                (
                    "previous_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "distribution_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "bulk_purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_logs",
                        to="billing.ispbulkpurchase",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributed_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_distribution_logs",
                "ordering": ["-distribution_date"],
            },
        ),
        migrations.CreateModel(
            name="CommissionTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to be settled to ISP",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("calculated", "Calculated"),
                            ("paid", "Paid to Platform"),
                            ("due", "Due to ISP"),
                            ("withheld", "Withheld"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_platform_share",
                    models.BooleanField(
                        default=True,
                        help_text="True if platform takes commission, False if ISP gets commission",
                    ),
                ),
                ("settlement_date", models.DateTimeField(blank=True, null=True)),
                ("settlement_reference", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bulk_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="billing.ispbulkpurchase",
                    ),
                ),
                (
                    "commission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.platformcommission",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="billing.payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_transactions",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "settlement_method",
                    models.CharField(
                        choices=[
                            ("paystack", "PayStack Transfer"),
                            ("bank_transfer", "Bank Transfer"),
                            ("wallet", "Platform Wallet"),
                            ("credit", "Platform Credit"),
                        ],
                        default="wallet",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("settlement_date", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission_transactions",
                    models.ManyToManyField(
                        related_name="settlements", to="billing.commissiontransaction"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_settlements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bulkdatapackage",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.datavendor",
            ),
        ),
    ]
