# Generated by Django 4.2.7 on 2025-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_bulkdatapackage_datavendor_platformcommission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paystack", "Paystack"),
                    ("mpesa", "M-Pesa"),
                    ("bank", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("manual", "Manual Entry"),
                ],
                default="paystack",
                max_length=20,
            ),
        ),
    ]
