# Generated by Django 4.2.7 on 2025-12-07 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0006_datawallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="ispbulkpurchase",
            name="wallet_deposited",
            field=models.BooleanField(
                default=False, verbose_name="Deposited to Wallet"
            ),
        ),
        migrations.AddField(
            model_name="ispbulkpurchase",
            name="wallet_deposited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("allocation", "Allocation to Customer"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_gb", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "previous_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("new_balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="billing.datawallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
