# Generated by Django 4.2.7 on 2025-12-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_ispbulkpurchase_wallet_deposited_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datadistributionlog",
            name="bulk_purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribution_logs",
                to="billing.ispbulkpurchase",
            ),
        ),
    ]
