# Generated by Django 4.2.7 on 2025-12-09 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_supportconversation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0008_alter_datadistributionlog_bulk_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="datawallet",
            name="allow_external_deposits",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="datawallet",
            name="max_external_deposit_per_day",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name="datawallet",
            name="require_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="external_reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="external_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="invoice_file",
            field=models.FileField(blank=True, null=True, upload_to="data_invoices/"),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("vendor_purchase", "Vendor Purchase"),
                    ("platform_purchase", "Platform Purchase"),
                    ("external_upload", "External Data Upload"),
                    ("invoice_upload", "Invoice Upload"),
                    ("api_deposit", "API Deposit"),
                    ("manual_entry", "Manual Entry"),
                ],
                default="vendor_purchase",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("allocation", "Allocation to Customer"),
                    ("refund", "Refund"),
                    ("external_deposit", "External Deposit"),
                    ("manual_adjustment", "Manual Adjustment"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExternalDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("isp_server", "ISP Own Server"),
                            ("external_api", "External API"),
                            ("csv_upload", "CSV Upload"),
                            ("manual_entry", "Manual Entry"),
                            ("invoice", "Invoice/Bill Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("api_endpoint", models.URLField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=500, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=500, null=True)),
                ("file_format", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync", models.BooleanField(default=False)),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual Only"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "total_deposits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "last_deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("last_deposit_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_data_sources",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "external_data_sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseConnectionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("sqlserver", "SQL Server"),
                            ("oracle", "Oracle"),
                            ("sqlite", "SQLite"),
                        ],
                        default="postgresql",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(max_length=200)),
                ("port", models.IntegerField(default=5432)),
                ("database", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("encrypted_password", models.BinaryField()),
                ("sync_customers", models.BooleanField(default=True)),
                ("sync_data_balance", models.BooleanField(default=True)),
                ("sync_transactions", models.BooleanField(default=False)),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("manual", "Manual Only"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_tested_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_sync_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_synced",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database_connections",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "database_connection_configs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="APIIntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("safaricom", "Safaricom Data API"),
                            ("airtel", "Airtel Data API"),
                            ("mtn", "MTN Data API"),
                            ("isp_system", "ISP Management System"),
                            ("data_vendor", "Third-party Data Vendor"),
                            ("custom", "Custom API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_endpoint", models.URLField()),
                ("api_key", models.CharField(blank=True, max_length=500, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "request_timeout",
                    models.IntegerField(default=30, help_text="Timeout in seconds"),
                ),
                ("retry_attempts", models.IntegerField(default=3)),
                ("auto_sync", models.BooleanField(default=False)),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual Only"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_tested_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_sync_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_synced",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_integrations",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "api_integration_configs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV File"),
                            ("excel", "Excel File"),
                            ("json", "JSON File"),
                            ("xml", "XML File"),
                            ("api", "API Import"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("row_number", models.IntegerField(blank=True, null=True)),
                ("amount_gb", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reference", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_imports",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "data_import_logs",
                "ordering": ["-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="data_import_tenant__bec680_idx",
                    ),
                    models.Index(
                        fields=["tenant", "import_type"],
                        name="data_import_tenant__970684_idx",
                    ),
                ],
            },
        ),
    ]
