# Generated by Django 4.2.7 on 2025-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0009_datawallet_allow_external_deposits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldatasource",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="api_secret",
            field=models.TextField(blank=True, null=True),
        ),
    ]
