# Generated by Django 4.2.7 on 2025-12-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("router_manager", "0004_routerconfig_last_checked_and_more"),
        ("accounts", "0016_rename_customer_supportconversation_user_and_more"),
        ("billing", "0010_alter_externaldatasource_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkBandwidthPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("dedicated", "Dedicated Bandwidth"),
                            ("shared", "Shared Bandwidth"),
                            ("burst", "Burst Bandwidth"),
                        ],
                        default="dedicated",
                        max_length=20,
                    ),
                ),
                (
                    "bandwidth_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount of bandwidth", max_digits=10
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("mbps", "Mbps"), ("gbps", "Gbps")],
                        default="mbps",
                        max_length=10,
                    ),
                ),
                ("base_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
                ),
                ("validity_days", models.IntegerField(default=30)),
                (
                    "upstream_commit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "downstream_commit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "burst_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bandwidth_packages",
                        to="billing.datavendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bandwidth Package",
                "verbose_name_plural": "Bandwidth Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ISPBandwidthPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "total_bandwidth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total bandwidth purchased",
                        max_digits=10,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "isp_net_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("completed", "Completed"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("activation_date", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "allocated_ip_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bandwidth_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.bulkbandwidthpackage",
                    ),
                ),
                (
                    "router_allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="router_manager.router",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bandwidth_purchases",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at"],
            },
        ),
    ]
