# Generated by Django 4.2.7 on 2025-12-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_rename_customer_supportconversation_user_and_more"),
        ("billing", "0011_bulkbandwidthpackage_ispbandwidthpurchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="ISPDataPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[("data", "Data"), ("bandwidth", "Bandwidth")],
                        default="data",
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "total_data_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total data in GB",
                        max_digits=10,
                    ),
                ),
                (
                    "total_bandwidth_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total bandwidth in Mbps",
                        max_digits=10,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "vendor_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "isp_net_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_method", models.CharField(default="paystack", max_length=50)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bulk_bandwidth_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.bulkbandwidthpackage",
                    ),
                ),
                (
                    "bulk_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.bulkdatapackage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_purchases",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISP Data Purchase",
                "verbose_name_plural": "ISP Data Purchases",
                "ordering": ["-purchased_at"],
            },
        ),
    ]
