# Generated by Django 4.2.7 on 2025-12-15 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0012_ispdatapurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="approval_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval Date"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription_activated",
            field=models.BooleanField(
                default=False, verbose_name="Subscription Auto-Activated"
            ),
        ),
    ]
