# Generated by Django 4.2.7 on 2025-12-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_payment_approval_date_payment_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ispdatapurchase",
            options={"ordering": ["-purchased_at"]},
        ),
        migrations.AddField(
            model_name="ispdatapurchase",
            name="vendor_commission_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="package_type",
            field=models.CharField(
                choices=[("data", "Data"), ("bandwidth", "Bandwidth")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paystack", "PayStack"),
                    ("wallet", "Wallet Balance"),
                    ("bank", "Bank Transfer"),
                ],
                default="paystack",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="platform_commission",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="total_bandwidth_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="total_data_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="vendor_commission",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
