# Generated by Django 4.2.7 on 2025-12-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0014_alter_ispdatapurchase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissiontransaction",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commissiontransaction",
            name="vendor_commission",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="commissiontransaction",
            name="vendor_commission_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
