# Generated by Django 4.2.7 on 2025-12-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0015_commissiontransaction_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissiontransaction",
            name="commission_type",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription"),
                    ("bulk_data", "Bulk Data"),
                    ("bandwidth", "Bandwidth"),
                    ("topup", "Top-up"),
                    ("one_time", "One-time Payment"),
                ],
                default="subscription",
                max_length=20,
            ),
        ),
    ]
