# Generated by Django 4.2.7 on 2025-12-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0016_commissiontransaction_commission_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissiontransaction",
            name="bandwidth_purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commissions",
                to="billing.ispbandwidthpurchase",
            ),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="bulk_purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commissions",
                to="billing.ispbulkpurchase",
            ),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="commission_type",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription"),
                    ("bulk_data", "Bulk Data"),
                    ("bandwidth", "Bandwidth"),
                    ("topup", "Top-up"),
                    ("one_time", "One-time Payment"),
                    ("bulk_purchase", "Bulk Purchase"),
                ],
                default="subscription",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="net_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount to be settled to ISP",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commission_transactions",
                to="billing.payment",
            ),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="vendor_commission",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="vendor_commission_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
