# Generated by Django 4.2.7 on 2025-12-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0017_commissiontransaction_bandwidth_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datawallet",
            name="balance_bandwidth_mbps",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="amount_mbps",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Bandwidth (Mbps)",
            ),
        ),
    ]
