# Generated by Django 4.2.7 on 2025-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0018_datawallet_balance_bandwidth_mbps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ispdatapurchase",
            name="wallet_deposited",
            field=models.BooleanField(
                default=False, verbose_name="Deposited to Wallet"
            ),
        ),
        migrations.AddField(
            model_name="ispdatapurchase",
            name="wallet_deposited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
