# Generated by Django 4.2.7 on 2025-12-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0020_ispbandwidthpurchase_wallet_deposited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="new_bandwidth_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="previous_bandwidth_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
