# Generated by Django 4.2.7 on 2025-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0021_wallettransaction_new_bandwidth_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallettransaction",
            name="new_bandwidth_balance",
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="previous_bandwidth_balance",
        ),
        migrations.AlterField(
            model_name="ispdatapurchase",
            name="package_type",
            field=models.CharField(
                choices=[("data", "Data"), ("bandwidth", "Bandwidth")],
                default="data",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount_gb",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="new_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="previous_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
