# Generated by Django 4.2.7 on 2025-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0022_remove_wallettransaction_new_bandwidth_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="public_key",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="secret_key",
            field=models.CharField(default="", max_length=255),
        ),
    ]
