# Generated by Django 4.2.7 on 2025-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0023_alter_paystackconfiguration_public_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="public_key",
            field=models.CharField(
                default="pk_test_326928d62c0d19eaa90341289573887d07a5c96c",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="secret_key",
            field=models.CharField(
                default="sk_test_c4b6dc6701d7915adeb41f275b6d8cec465b2d1d",
                max_length=255,
            ),
        ),
    ]
