# Generated by Django 4.2.7 on 2025-12-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0024_alter_paystackconfiguration_public_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paystackconfiguration",
            name="secret_key",
            field=models.CharField(
                default="sk_test_a38271e5a19686576e1d775df3f2d42b2027a242",
                max_length=255,
            ),
        ),
    ]
