# Generated by Django 4.2.7 on 2025-11-19 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginhistory_usersession_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "login_activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("subdomain", models.CharField(max_length=100, unique=True)),
                ("custom_domain", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                ("primary_color", models.CharField(default="#4361ee", max_length=7)),
                ("secondary_color", models.CharField(default="#3a0ca3", max_length=7)),
                ("bandwidth_limit", models.IntegerField(default=1000)),
                ("client_limit", models.IntegerField(default=1000)),
                ("auto_disconnect_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants",
            },
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="custom_user_email_c8f161_idx",
            old_name="accounts_cu_email_5ce40b_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="custom_user_company_116ef4_idx",
            old_name="accounts_cu_company_c894e9_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="custom_user_is_acti_f5beb2_idx",
            old_name="accounts_cu_is_acti_2885e2_idx",
        ),
        migrations.AddField(
            model_name="customuser",
            name="account_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bandwidth_limit",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="data_usage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_active_customer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="next_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("isp_admin", "ISP Administrator"),
                    ("isp_staff", "ISP Staff"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_plan",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="custom_users",
        ),
        migrations.AddField(
            model_name="loginactivity",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_activities",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="loginactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customuser",
            unique_together={("tenant", "company_account_number")},
        ),
    ]
