# Generated by Django 4.2.7 on 2025-11-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_loginactivity_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company_account_number",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
