# Generated by Django 4.2.7 on 2025-11-24 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_approval_date_customuser_approved_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bandwidth_limit",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="data_usage",
        ),
    ]
