# Generated by Django 4.2.7 on 2025-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_customuser_bandwidth_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="accent_color",
            field=models.CharField(default="#f59e0b", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="dark_color",
            field=models.CharField(default="#1e3a8a", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="light_color",
            field=models.CharField(default="#eff6ff", max_length=7),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(default="#2563eb", max_length=7),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(default="#7c3aed", max_length=7),
        ),
    ]
