# Generated by Django 4.2.7 on 2025-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_tenant_accent_color_tenant_dark_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="error_color",
            field=models.CharField(default="#ef4444", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="info_color",
            field=models.CharField(default="#3b82f6", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="success_color",
            field=models.CharField(default="#10b981", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="text_color",
            field=models.CharField(default="#1f2937", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="warning_color",
            field=models.CharField(default="#f59e0b", max_length=7),
        ),
    ]
