# Generated by Django 4.2.7 on 2025-12-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_tenant_error_color_tenant_info_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_admin", "Create Admin"),
                            ("toggle_admin_status", "Toggle Admin Status"),
                            ("remove_admin", "Remove Admin"),
                            ("send_password_reset", "Send Password Reset"),
                            ("edit_permissions", "Edit Permissions"),
                            ("login", "Admin Login"),
                            ("logout", "Admin Logout"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_logs",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "timestamp"],
                        name="accounts_ad_tenant__6443aa_idx",
                    ),
                    models.Index(
                        fields=["admin", "timestamp"],
                        name="accounts_ad_admin_i_863784_idx",
                    ),
                ],
            },
        ),
    ]
