# Generated by Django 4.2.7 on 2025-12-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_adminlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bandwidth_limit",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="data_usage",
            field=models.FloatField(default=0),
        ),
    ]
