# Generated by Django 4.2.7 on 2025-12-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_customuser_bandwidth_limit_customuser_data_usage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "verbose_name": "ISP Provider",
                "verbose_name_plural": "ISP Providers",
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="bank_details",
            field=models.FileField(
                blank=True, null=True, upload_to="tenant_docs/bank_details/"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="business_registration",
            field=models.FileField(
                blank=True, null=True, upload_to="tenant_docs/business_registration/"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="business_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_position",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="id_document",
            field=models.FileField(
                blank=True, null=True, upload_to="tenant_docs/id_document/"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tax_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="tenant_docs/tax_certificate/"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tax_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="verification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="years_in_operation",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
