# Generated by Django 4.2.7 on 2025-12-08 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_supportconversation_alter_loginhistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportconversation",
            options={"ordering": ["-last_message_at"]},
        ),
        migrations.RenameField(
            model_name="supportconversation",
            old_name="is_open",
            new_name="is_read_by_customer",
        ),
        migrations.RemoveField(
            model_name="supportconversation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="sender_type",
        ),
        migrations.AddField(
            model_name="supportconversation",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportconversation",
            name="category",
            field=models.CharField(
                choices=[
                    ("billing", "Billing"),
                    ("technical", "Technical"),
                    ("account", "Account"),
                    ("service", "Service"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="supportconversation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportconversation",
            name="is_read_by_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supportconversation",
            name="last_message_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="supportconversation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supportconversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="support_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="supportconversation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supportconversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supportconversation",
            name="subject",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="supportmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supportmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supportmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SupportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="support_attachments/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.IntegerField()),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="accounts.supportmessage",
                    ),
                ),
            ],
            options={
                "db_table": "support_attachments",
            },
        ),
    ]
