# Generated by Django 4.2.7 on 2025-12-10 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_supportconversation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="geocoded_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="geocoded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate for mapping",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate for mapping",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, help_text="Full address"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, default="Kenya", max_length=100),
        ),
        migrations.CreateModel(
            name="ISPZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("geojson", models.JSONField(blank=True, null=True)),
                ("min_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("max_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("min_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("max_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("customer_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="Kenya", max_length=100),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("gps", "GPS Device"),
                            ("browser", "Browser Geolocation"),
                            ("geocode", "Address Geocoding"),
                            ("admin", "Admin Set"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_customer_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
