# Generated by Django 4.2.7 on 2025-12-11 10:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0015_customuser_geocoded_address_customuser_geocoded_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="supportconversation",
            old_name="customer",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name="customerlocation",
            index=models.Index(
                fields=["customer", "is_primary"], name="accounts_cu_custome_99cc79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["latitude", "longitude"], name="custom_user_latitud_0bcb71_idx"
            ),
        ),
    ]
