# Generated by Django 4.2.7 on 2025-12-19 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_verificationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("create_user", "Create User"),
                            ("update_user", "Update User"),
                            ("delete_user", "Delete User"),
                            ("mark_payment_completed", "Mark Payment Completed"),
                            ("update_payment_status", "Update Payment Status"),
                            ("delete_payment", "Delete Payment"),
                            ("send_receipt", "Send Receipt"),
                            ("bulk_payment_action", "Bulk Payment Action"),
                            ("create_subscription", "Create Subscription"),
                            ("update_subscription", "Update Subscription"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
