# Generated by Django 4.2.7 on 2025-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_update_customerlocation_country_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
