# Generated by Django 4.2.7 on 2025-12-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_customuser_otp_created_at_customuser_otp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True, help_text="Physical business address"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="description",
            field=models.TextField(
                blank=True, help_text="Business description or notes"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="monthly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Monthly subscription rate in local currency",
                max_digits=10,
                null=True,
            ),
        ),
    ]
