# Generated by Django 4.2.7 on 2025-11-19 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_loginactivity_tenant_and_more"),
        (
            "router_manager",
            "0002_guestnetwork_routerlog_alter_connecteddevice_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RouterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "router_type",
                    models.CharField(
                        choices=[
                            ("huawei", "Huawei"),
                            ("tenda", "Tenda"),
                            ("mikrotik", "MikroTik"),
                            ("ubiquiti", "Ubiquiti"),
                            ("tplink", "TP-Link"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("router_model", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField()),
                ("username", models.CharField(default="admin", max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("web_port", models.IntegerField(default=80)),
                ("is_online", models.BooleanField(default=False)),
                ("huawei_ont_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routers",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortForwardingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_port", models.IntegerField()),
                ("internal_ip", models.GenericIPAddressField()),
                ("internal_port", models.IntegerField()),
                (
                    "protocol",
                    models.CharField(
                        choices=[("tcp", "TCP"), ("udp", "UDP"), ("both", "Both")],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_rules",
                        to="router_manager.routerconfig",
                    ),
                ),
            ],
            options={
                "db_table": "port_forwarding_rules",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mac_address", models.CharField(max_length=17)),
                ("ip_address", models.GenericIPAddressField()),
                ("device_name", models.CharField(blank=True, max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("computer", "Computer"),
                            ("phone", "Phone"),
                            ("tablet", "Tablet"),
                            ("iot", "IoT Device"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("data_usage", models.FloatField(default=0)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="router_manager.routerconfig",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "unique_together": {("tenant", "mac_address")},
            },
        ),
    ]
