# Generated by Django 4.2.7 on 2025-11-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_customuser_bandwidth_limit_and_more"),
        ("router_manager", "0003_routerconfig_portforwardingrule_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="routerconfig",
            name="last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="connecteddevice",
            name="router",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connected_devices",
                to="router_manager.router",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="router",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="router_manager.router",
            ),
        ),
        migrations.AlterField(
            model_name="routerconfig",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="router_configs",
                to="accounts.tenant",
            ),
        ),
    ]
