# Generated by Django 4.2.7 on 2025-12-25 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("router_manager", "0005_parentalcontrolschedule_firmwareupdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firmwareupdate",
            options={"ordering": ["-release_date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="parentalcontrolschedule",
            options={"ordering": ["-is_active", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="firmwareupdate",
            old_name="started_at",
            new_name="installed_at",
        ),
        migrations.RemoveField(
            model_name="firmwareupdate",
            name="completed_at",
        ),
        migrations.AddField(
            model_name="firmwareupdate",
            name="auto_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="firmwareupdate",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firmwareupdate",
            name="requires_reboot",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="firmwareupdate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="parentalcontrolschedule",
            name="apply_to_all",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="parentalcontrolschedule",
            name="block_gaming",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parentalcontrolschedule",
            name="block_social_media",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parentalcontrolschedule",
            name="block_streaming",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parentalcontrolschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="parentalcontrolschedule",
            name="custom_sites",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="parentalcontrolschedule",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("time", "Time-based"),
                    ("always", "Always Block"),
                    ("bedtime", "Bedtime"),
                    ("study", "Study Time"),
                    ("custom", "Custom"),
                ],
                default="time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="firmwareupdate",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="firmwareupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("downloading", "Downloading"),
                    ("installing", "Installing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("scheduled", "Scheduled"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="parentalcontrolschedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parentalcontrolschedule",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
