# Generated by Django 4.2.7 on 2025-12-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_tenant_address_tenant_description_and_more"),
        ("router_manager", "0006_alter_firmwareupdate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routers",
                to="accounts.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="portforwardingrule",
            name="router",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_rules",
                to="router_manager.router",
            ),
        ),
    ]
