# Generated by Django 4.2.7 on 2025-12-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("router_manager", "0007_router_tenant_alter_portforwardingrule_router"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routerconfig",
            options={
                "ordering": ["-is_available", "-created_at"],
                "verbose_name": "Router Configuration",
                "verbose_name_plural": "Router Configurations",
            },
        ),
        migrations.AddField(
            model_name="router",
            name="router_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to ISP-managed router configuration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_routers",
                to="router_manager.routerconfig",
                verbose_name="ISP Router Configuration",
            ),
        ),
        migrations.AddField(
            model_name="routerconfig",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "customer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_routers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Customer",
            ),
        ),
        migrations.AddField(
            model_name="routerconfig",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Check if this router is available for assignment to customers",
                verbose_name="Available for Assignment",
            ),
        ),
    ]
